Error: object 'datA_ready' not found 
Traceback: 
No traceback available 
